#What will be the result of the following code:
x = 5
y = 8
if x > y:
  print('Hello')
else:
  print('Welcome')
#Welcome

#Print "Hello World" if a is greater than b.
a = 50
b = 10
if a > b:
  print("Hello World")

#Print "Hello World" if a is not equal to b.
a = 50
b = 10
if a != b:
    print("Hello World")
    
#Print "Yes" if a is equal to b, otherwise print "No".
a = 50
b = 10
if a == b:
  print("Yes")
else:
  print("No")


a = 50
b = 10
if a == b:
  print("1")
elif a > b:
  print("2")
else:
  print("3")
  

if a == b and c == d:
  print("Hello")

if a == b or c == d:
  print("Hello")

if 5 > 2:
    print("YES")


a = 2
b = 5
print("YES") if a == b else  print("NO")